"""Add groups, runners and legs columns to df

Revision ID: e1c9896e9f00
Revises: 61c98c09d73f
Create Date: 2024-09-09 18:43:05.912986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1c9896e9f00'
down_revision: Union[str, None] = '61c98c09d73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('groups', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('events', sa.Column('runners', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('events', sa.Column('legs', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'legs')
    op.drop_column('events', 'runners')
    op.drop_column('events', 'groups')
    # ### end Alembic commands ###
